# Generated by Django 6.1.1 on 2026-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
